export const USERS_SERVICE_URL = process.env.NEXT_PUBLIC_USER_SERVICE_URL
export const PROJECT_SERVICE_URL = process.env.NEXT_PUBLIC_PROJECT_SERVICE_URL
export const TASK_SERVICE_URL = process.env.NEXT_PUBLIC_TASK_SERVICE_URL
export const CHAT_SERVICE_URL = process.env.NEXT_PUBLIC_CHAT_SERVICE_URL
export const NOTIFICATION_SERVICE_URL = process.env.NEXT_PUBLIC_NOTIFICATION_SERVICE_URL